name: familiahuecasfrontend
description: "front en flutter de familia huecas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <3.6.0"  # Ajustado para ser compatible con Dart 3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.6.0
  cupertino_icons: ^1.0.8
  web: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.6.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
