name: familiahuecasfrontend
description: "front en flutter de familia huecas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.6.0
  cupertino_icons: ^1.0.8
  web: ^1.1.0
  file_picker: ^5.0.0
  animated_tree_view: ^2.3.0
  open_filex: ^4.0.2
  file_saver: ^0.0.7
  mime: ^1.0.0
  dio: ^5.2.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.6.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/olivoFHsinfondo.png